name: Dev to QA Tests

on:
  pull_request:
    branches:
      - qa
    types: [opened, synchronize, reopened]

jobs:
  check_source_branch:
    name: Check source branch
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch is dev
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "This workflow is only for PRs from dev to qa"
            exit 1
          fi
        shell: bash

  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: check_source_branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install flake8 black isort bandit

      # - name: Run flake8
      #   run: flake8 src tests
      
      # - name: Run black
      #   run: black --check src tests
      
      - name: Run isort
        run: isort --check-only --profile black src tests
      
      - name: Run bandit security check
        run: bandit -r src

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: check_source_branch
    container:
      image: databricksruntime/python:15.3-LTS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
      
      - name: Run unit tests
        run: pytest -xvs tests/
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          
  validate_databricks_bundle:
    name: Validate Databricks Bundle
    runs-on: ubuntu-latest
    needs: check_source_branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install databricks-cli
        run: pip install databricks-cli

      - name: Validate bundle format
        run: |
          databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }} 