name: QA to PRD Validation

on:
  pull_request:
    branches:
      - prd
    types: [opened, synchronize, reopened]

jobs:
  check_source_branch:
    name: Check source branch
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch is qa
        run: |
          if [[ "${{ github.head_ref }}" != "qa" ]]; then
            echo "This workflow is only for PRs from qa to prd"
            exit 1
          fi
        shell: bash

  validate_bundle:
    name: Validate Bundle
    needs: check_source_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow checkout para melhorar performance
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Databricks CLI
        run: |
          echo "Instalando o CLI do Databricks..."
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          # Verificar se o CLI foi instalado corretamente
          which databricks
          
      - name: Validate bundle format
        run: |
          databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }} 